### ISSUE TITLE
add support for jekyll 3.0

### ISSUE THREAD

**Issue by dominikwilkowski** [dannygarcia/grunt-jekyll#74]
Hey there,

Is this project dead or can we expect an update for the new jekyll 3?
http://jekyllrb.com/news/2015/10/26/jekyll-3-0-released/

**Comment by hitchcockwill** [comment]
Last commit on 5/25/15 - not looking good.

**Comment by dannygarcia** [comment]
I'm seeking a maintainer for this project. If anyone's interested please let me know and I'll grant them rights to maintain/publish.

**Comment by dominikwilkowski** [comment]
interesting... Let me have a look

**Comment by dominikwilkowski** [comment]
Your coding style looks great. Would love to have a stab but give me a week to get stuff done first so I actually have some time.

**Comment by dominikwilkowski** [comment]
well looks like jekyll 3.0 runs just fine... :)
some preferences may not be supported like `--incremental` but for the most parts....

Closing this as not explicit enough

**Comment by sparanoid** [comment]
Hi @dannygarcia, I use grunt-jekyll in a lot of projects, If nobody is interested in the maintaining this project, I would like to help!

**Comment by dannygarcia** [comment]
@dominikwilkowski thanks just send me a private message (email or something) when you're ready.

@sparanoid thanks can you send me private message (email or something) with your npm username?
I've added you as a collaborator to this.
